# Default values for gpu-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nfd:
  enabled: true

node-feature-discovery:
  worker:
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"

    options:
      sources:
        pci:
          deviceLabelFields:
          - vendor

platform:
  openshift: false

operator:
  repository: nvidia
  image: gpu-operator
# If not set, the tag defaults to Chart.AppVersion
# tag: "foo"

  defaultRuntime: docker
  clusterversion: 0.0

  nodeSelector: {}

  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"

  annotations:
    openshift.io/scc: restricted-readonly

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]

driver:
  repository: nvidia
  image: nvidia-driver2/ubuntu
  version: 18.04-ppc64le

toolkit:
  repository: nvidia
  image: container-toolkit/ubuntu18.04
  version: latest

devicePlugin:
  repository: nvidia
  image: k8s-device-plugin
  version: 1.0.0-beta6

dcgmExporter:
  repository: nvidia
  image: dcgm-exporter
  version: 1.7.2-2.0.0-rc.6-ubuntu18.04
