apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-driver-validation
  name: nvidia-driver-validation
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "mrobbo/samples:cuda10.2-vectorAdd"
      securityContext:
        allowPrivilegeEscalation: false
  nodeSelector:
    feature.node.kubernetes.io/pci-10de.present: "true"
